import{and,eq}from"drizzle-orm";import{db}from"../database/client.js";import{alerts,pushDevices,users}from"../database/schema.js";import{log}from"../shared/log.js";import{createPushProvider,type PushMessage}from"./provider.js";
type AlertEvent={id:string;serverId:string;severity:string;title:string;message:string};
export class NotificationService{
 readonly provider=createPushProvider();
 async sendAlert(alert:AlertEvent,recovery=false){const result=await this.sendToAll({title:recovery?`Resolved: ${alert.title}`:alert.title,body:recovery?`Recovered — ${alert.message}`:alert.message,alertId:alert.id,serverId:alert.serverId,severity:alert.severity,category:"SERVER_ALERT"});await db.update(alerts).set({notificationStatus:result.failed?"partial":result.sent?"sent":"no_devices"}).where(eq(alerts.id,alert.id));}
 async sendTest(userId:string){const user=await db.query.users.findFirst({where:eq(users.id,userId)});if(!user)throw new Error("USER_NOT_FOUND");return this.deliver(await db.select().from(pushDevices).where(and(eq(pushDevices.userId,userId),eq(pushDevices.enabled,true))),{title:"Nas Hub test notification",body:"Push notifications are configured correctly.",severity:"info",category:"SERVER_ALERT"});}
 private async sendToAll(message:PushMessage){return this.deliver(await db.select().from(pushDevices).where(eq(pushDevices.enabled,true)),message);}
 private async deliver(devices:typeof pushDevices.$inferSelect[],message:PushMessage){let sent=0,failed=0;for(const device of devices){try{const result=await this.provider.send(device.token,device.topic,message);if(result.success){sent++;log.info({deviceId:device.id,status:result.status},"push notification sent");}else{failed++;log.warn({deviceId:device.id,status:result.status,reason:result.reason},"push notification rejected");if(result.invalidToken)await db.update(pushDevices).set({enabled:false}).where(eq(pushDevices.id,device.id));}}catch(error){failed++;log.error({error,deviceId:device.id},"push notification failed");}}return{sent,failed,provider:this.provider.status};}
}
