import { integer, real, sqliteTable, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", { id: text().primaryKey(), username: text().notNull(), email: text().notNull(), passwordHash: text("password_hash").notNull(), role: text().notNull().default("admin"), setupCompleted: integer("setup_completed",{mode:"boolean"}).notNull().default(false), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(), disabled: integer({mode:"boolean"}).notNull().default(false) }, t => [uniqueIndex("users_username_uq").on(t.username), uniqueIndex("users_email_uq").on(t.email)]);
export const sessions = sqliteTable("sessions", { id: text().primaryKey(), userId: text("user_id").notNull().references(()=>users.id), refreshTokenHash: text("refresh_token_hash").notNull(), deviceDescription: text("device_description"), createdAt: integer("created_at").notNull(), expiresAt: integer("expires_at").notNull(), revokedAt: integer("revoked_at"), lastUsedAt: integer("last_used_at").notNull() }, t => [index("sessions_user_idx").on(t.userId)]);
export const servers = sqliteTable("servers", { id: text().primaryKey(), name: text().notNull(), hostname: text().notNull(), operatingSystem: text("operating_system").notNull(), architecture: text().notNull(), version: text().notNull(), lastSeenAt: integer("last_seen_at"), createdAt: integer("created_at").notNull() });
export const metricSamples = sqliteTable("metric_samples", { id: integer().primaryKey({autoIncrement:true}), serverId: text("server_id").notNull().references(()=>servers.id), timestamp: integer().notNull(), resolution: text().notNull().default("raw"), publicIPv4:text("public_ipv4"),cpuPercent: real("cpu_percent"),systemUtilization:real("system_utilization"), perCoreJson: text("per_core_json"), load1: real(), load5: real(), load15: real(), ramTotal: integer("ram_total"), ramUsed: integer("ram_used"), ramAvailable: integer("ram_available"), ramPercent: real("ram_percent"), swapTotal: integer("swap_total"), swapUsed: integer("swap_used"), diskTotal: integer("disk_total"), diskUsed: integer("disk_used"), diskAvailable: integer("disk_available"), diskPercent: real("disk_percent"),diskBusyPercent:real("disk_busy_percent"),diskDeviceCount:integer("disk_device_count").notNull().default(0), diskReadBps: real("disk_read_bps"), diskWriteBps: real("disk_write_bps"), networkRxBps: real("network_rx_bps"), networkTxBps: real("network_tx_bps"), uptime: real(), processCount: integer("process_count"), temperature: real(), bootTime: integer("boot_time") }, t => [index("metrics_server_time_idx").on(t.serverId,t.timestamp,t.resolution)]);
export const watchdogRules = sqliteTable("watchdog_rules", { id: text().primaryKey(), serverId: text("server_id").notNull(), metric: text().notNull(), severity: text().notNull(), warningThreshold: real("warning_threshold"), criticalThreshold: real("critical_threshold").notNull(), recoveryThreshold: real("recovery_threshold").notNull(), requiredDuration: integer("required_duration").notNull(), cooldown: integer().notNull(), enabled: integer({mode:"boolean"}).notNull().default(true), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() });
export const alerts = sqliteTable("alerts", { id: text().primaryKey(), serverId: text("server_id").notNull(), ruleId: text("rule_id").notNull(), severity: text().notNull(), status: text().notNull(), title: text().notNull(), message: text().notNull(), metricValue: real("metric_value"), thresholdValue: real("threshold_value"), triggeredAt: integer("triggered_at").notNull(), acknowledgedAt: integer("acknowledged_at"), resolvedAt: integer("resolved_at"), notificationStatus: text("notification_status").notNull().default("pending") }, t => [index("alerts_status_idx").on(t.status,t.triggeredAt)]);
export const pushDevices = sqliteTable("push_devices", { id: text().primaryKey(), userId: text("user_id").notNull(), token: text().notNull(), environment: text().notNull(), topic: text().notNull(), deviceName: text("device_name"), lastSeenAt: integer("last_seen_at").notNull(), enabled: integer({mode:"boolean"}).notNull().default(true) }, t => [uniqueIndex("push_token_uq").on(t.token)]);
