import type {IncomingMessage,ServerResponse} from "node:http";import {z} from "zod";import {and,asc,desc,eq,gte,lte} from "drizzle-orm";import {db} from "../database/client.js";import {alerts,metricSamples,pushDevices,servers,users,watchdogRules}from"../database/schema.js";import type{AuthService,Principal}from"../auth/service.js";import type{MetricCollector}from"../metrics/collector.js";import type{WebSocketHub}from"../websocket/hub.js";import{body,failure,json,ok}from"../shared/http.js";import{LoginLimiter}from"../auth/rate-limit.js";import{randomUUID}from"node:crypto";import{LOCAL_SERVER_ID}from"../metrics/collector.js";
const loginSchema=z.object({identifier:z.string().min(1),password:z.string().min(1),deviceDescription:z.string().max(200).optional()});const tokenSchema=z.object({refreshToken:z.string()});const pushSchema=z.object({token:z.string().min(20),environment:z.enum(["development","production"]),topic:z.string(),deviceName:z.string().optional()});
export class ApiRouter{private limiter=new LoginLimiter();constructor(private auth:AuthService,private collector:MetricCollector,private hub:WebSocketHub){}
 async handle(req:IncomingMessage,res:ServerResponse):Promise<boolean>{const url=new URL(req.url??"/","http://localhost");if(!url.pathname.startsWith("/api/v1/"))return false;try{
  if(req.method==="POST"&&url.pathname==="/api/v1/auth/login"){const key=req.socket.remoteAddress??"unknown";if(!this.limiter.allow(key))return void json(res,429,failure("RATE_LIMITED","Try again later")),true;const input=loginSchema.parse(await body(req)),tokens=await this.auth.login(input.identifier,input.password,input.deviceDescription);if(!tokens)return void json(res,401,failure("INVALID_CREDENTIALS","Invalid username/email or password")),true;this.limiter.clear(key);return void json(res,200,ok(tokens)),true;}
  if(req.method==="POST"&&url.pathname==="/api/v1/auth/refresh"){const input=tokenSchema.parse(await body(req)),tokens=await this.auth.refresh(input.refreshToken);return void json(res,tokens?200:401,tokens?ok(tokens):failure("INVALID_REFRESH_TOKEN","Session is invalid or expired")),true;}
  if(req.method==="POST"&&url.pathname==="/api/v1/auth/logout"){const input=tokenSchema.parse(await body(req));await this.auth.logout(input.refreshToken);return void json(res,204,{}),true;}
  if(req.method==="GET"&&url.pathname==="/api/v1/system/health")return void json(res,200,ok({status:"ok",database:"ok",metricCollector:this.collector.healthy?"ok":"degraded",websocketConnections:this.hub.connections,apns:"mock",version:"0.1.0",uptime:process.uptime()})),true;
  const principal=await this.principal(req);if(!principal)return void json(res,401,failure("UNAUTHORIZED","Authentication required")),true;
  if(req.method==="GET"&&url.pathname==="/api/v1/auth/me"){const user=await db.query.users.findFirst({where:eq(users.id,principal.sub),columns:{passwordHash:false}});return void json(res,200,ok(user)),true;}
  if(req.method==="GET"&&url.pathname==="/api/v1/servers")return void json(res,200,ok(await db.select().from(servers))),true;
  if(req.method==="GET"&&url.pathname===`/api/v1/servers/${LOCAL_SERVER_ID}/metrics/current`)return void json(res,200,ok(this.collector.current)),true;
  if(req.method==="GET"&&url.pathname===`/api/v1/servers/${LOCAL_SERVER_ID}/health`){const active=await db.select().from(alerts).where(eq(alerts.status,"active"));return void json(res,200,ok({serverId:LOCAL_SERVER_ID,status:active.some(a=>a.severity==="critical")?"critical":active.length?"warning":this.collector.healthy?"healthy":"unknown",activeAlertCount:active.length,lastUpdated:this.collector.current?.timestamp??null,metrics:this.collector.current})),true;}
  if(req.method==="GET"&&url.pathname===`/api/v1/servers/${LOCAL_SERVER_ID}/metrics/history`){const start=Number(url.searchParams.get("start")??Date.now()-3600000),end=Number(url.searchParams.get("end")??Date.now()),limit=Math.min(Number(url.searchParams.get("maxPoints")??300),1000);const rows=await db.select().from(metricSamples).where(and(eq(metricSamples.serverId,LOCAL_SERVER_ID),gte(metricSamples.timestamp,start),lte(metricSamples.timestamp,end))).orderBy(asc(metricSamples.timestamp)).limit(limit);return void json(res,200,ok(rows)),true;}
  if(req.method==="GET"&&url.pathname==="/api/v1/alerts")return void json(res,200,ok(await db.select().from(alerts).orderBy(desc(alerts.triggeredAt)).limit(200))),true;
  const ack=url.pathname.match(/^\/api\/v1\/alerts\/([^/]+)\/acknowledge$/);if(req.method==="POST"&&ack){await db.update(alerts).set({acknowledgedAt:Date.now()}).where(eq(alerts.id,ack[1]!));return void json(res,200,ok({acknowledged:true})),true;}
  if(req.method==="GET"&&url.pathname==="/api/v1/watchdog/rules")return void json(res,200,ok(await db.select().from(watchdogRules))),true;
  if(req.method==="POST"&&url.pathname==="/api/v1/push/devices"){const input=pushSchema.parse(await body(req)),now=Date.now(),id=randomUUID();await db.insert(pushDevices).values({id,userId:principal.sub,token:input.token,environment:input.environment,topic:input.topic,deviceName:input.deviceName,lastSeenAt:now}).onConflictDoUpdate({target:pushDevices.token,set:{userId:principal.sub,lastSeenAt:now,enabled:true}});return void json(res,201,ok({id})),true;}
  if(req.method==="POST"&&url.pathname==="/api/v1/push/test"){if(principal.role!=="admin")return void json(res,403,failure("FORBIDDEN","Administrator access required")),true;return void json(res,200,ok({acknowledged:true,provider:"mock"})),true;}
  return void json(res,404,failure("NOT_FOUND","Route not found")),true;
 }catch(error){if(error instanceof z.ZodError)return void json(res,400,failure("VALIDATION_ERROR",z.prettifyError(error))),true;return void json(res,500,failure("INTERNAL_ERROR","An unexpected error occurred")),true;}}
 private async principal(req:IncomingMessage):Promise<Principal|null>{const value=req.headers.authorization;if(!value?.startsWith("Bearer "))return null;try{return await this.auth.verifyAccess(value.slice(7));}catch{return null;}}
}
