import { and, eq } from "drizzle-orm";
import { randomUUID } from "node:crypto";
import { EventEmitter } from "node:events";
import { db } from "../database/client.js"; import { alerts,watchdogRules } from "../database/schema.js"; import type { Metric } from "../metrics/types.js"; import { LOCAL_SERVER_ID } from "../metrics/collector.js"; import { log } from "../shared/log.js";
export class WatchdogService extends EventEmitter {
 private since=new Map<string,number>();
 constructor(){super();}
 async seed(){const existing=await db.query.watchdogRules.findFirst();if(existing)return;const now=Date.now();for(const r of [{metric:"cpuPercent",severity:"critical",threshold:90,recovery:85,duration:300},{metric:"ramPercent",severity:"warning",threshold:90,recovery:85,duration:180},{metric:"ramPercent",severity:"critical",threshold:97,recovery:92,duration:60},{metric:"diskPercent",severity:"warning",threshold:85,recovery:80,duration:0},{metric:"diskPercent",severity:"critical",threshold:95,recovery:90,duration:0}])await db.insert(watchdogRules).values({id:randomUUID(),serverId:LOCAL_SERVER_ID,metric:r.metric,severity:r.severity,criticalThreshold:r.threshold,recoveryThreshold:r.recovery,requiredDuration:r.duration,cooldown:900,enabled:true,createdAt:now,updatedAt:now});}
 async evaluate(m:Metric){const rules=await db.query.watchdogRules.findMany({where:eq(watchdogRules.enabled,true)});for(const rule of rules){const value=m[rule.metric as keyof Metric];if(typeof value!=="number")continue;const active=await db.query.alerts.findFirst({where:and(eq(alerts.ruleId,rule.id),eq(alerts.status,"active"))});if(value>=rule.criticalThreshold){const start=this.since.get(rule.id)??m.timestamp;this.since.set(rule.id,start);if(!active&&m.timestamp-start>=rule.requiredDuration*1000){const title=`${rule.severity==="critical"?"Critical":"High"} ${rule.metric}`;const alert={id:randomUUID(),serverId:rule.serverId,ruleId:rule.id,severity:rule.severity,status:"active",title,message:`${rule.metric} is ${value.toFixed(1)} (threshold ${rule.criticalThreshold})`,metricValue:value,thresholdValue:rule.criticalThreshold,triggeredAt:m.timestamp,notificationStatus:"pending"};await db.insert(alerts).values(alert);this.emit("alert.created",alert);log.warn({alertId:alert.id,metric:rule.metric},"watchdog alert created");}}
 else if(value<=rule.recoveryThreshold){this.since.delete(rule.id);if(active){const resolved={...active,status:"resolved",resolvedAt:m.timestamp};await db.update(alerts).set({status:"resolved",resolvedAt:m.timestamp}).where(eq(alerts.id,active.id));this.emit("alert.resolved",resolved);log.info({alertId:active.id},"watchdog alert resolved");}}}}
}
